# Generated by Django 4.2.7 on 2024-03-12 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("in_tasix", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("visitors_number", models.PositiveIntegerField(default=0)),
                ("views_number", models.PositiveIntegerField(default=0)),
                (
                    "test_date",
                    models.DateField(
                        default=datetime.datetime(2024, 3, 12, 11, 46, 29, 713853, tzinfo=datetime.timezone.utc)
                    ),
                ),
                ("categories", models.ManyToManyField(related_name="sites", to="main.category")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statistic_type",
                    models.CharField(
                        choices=[
                            ("Visitors", "Visitors"),
                            ("Browsers", "Browser"),
                            ("Providers", "Provider"),
                            ("Countries", "Country"),
                            ("Oses", "Os"),
                            ("ScreensResolution", "Screen Res"),
                            ("EntryPoints", "Entry Point"),
                            ("ExitsPoints", "Exit Point"),
                            ("SearchEngines", "Search Engine"),
                            ("Devices", "Device"),
                        ],
                        max_length=31,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("extra", models.CharField(blank=True, max_length=31, null=True)),
                ("visitors_number", models.PositiveIntegerField(default=0)),
                ("visitors_tas_ix", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField()),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.site")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
