# Generated by Django 4.2.7 on 2024-03-12 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_category_code_alter_statistic_statistic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="test_date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 12, 11, 6, 13, 596647, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
